# My Variables
@contentType = application/json
@baseurl = http://localhost:4000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzkzNGQ2OTYyNzVlM2E2NjY2MDhjMzYiLCJpYXQiOjE2NzA1OTc5OTQsImV4cCI6MTY3MDg1NzE5NH0.YiSnX0BvlM5EHNyzxlbCE5OyOkd-_a8TVc0-IPJsNx0



### login
POST  {{baseurl}}/user/login
Content-Type: {{contentType}}

{
    "email": "giu@metropolia.fi",
    "password": "Hellohelsinki2!"
}


